### ISSUE TITLE
Stats command?

### ISSUE THREAD

**Issue by lorypelli** [Benricheson101/discord-2048#3]
Is it a good thing?
It will show
- Total games played by a user (we can also mention one)
- Total games wins by that user
- Maybe some stats of the bot? Like total games played on the bot, ram usage, cpu usage, total servers and users...

**Comment by Benricheson101** [comment]
Not possible unfortunately. The bot does not have a database so game stats can't be tracked. Additionally, Discord does not provide a way to get stats like server count for non-bot apps.
